name: "Create Document"

on:
  schedule:
    - cron: '20 7 * * *'
  workflow_dispatch:

permissions:
  id-token: write
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write


env:
  AWS_REGION: ap-northeast-1

defaults:
  run:
    shell: bash
    working-directory: "./"

jobs:
  checkout_repository:
    name: "Checkout Repository"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  create_document:
    name: "Create Document"
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
      - name: Create Document
        run: |
          ./resource_list.sh ECR
  git_commit:
    name: "Git Commit"
    runs-on: ubuntu-latest
    steps:
      - name: Count changes
        id: changes
        run: |
          git add -N .
          echo "count=$(git diff --name-only | wc -l)" >> $GITHUB_OUTPUT
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "$(TZ=Asia/Tokyo date '+%Y/%m/%d %H:%M:%S')"
          git push
        if: steps.changes.outputs.count > 0
